### PR TITLE
feat: Added navbar component

### PR DESCRIPTION
**Pull request by patel-aaryan**
- Added navbar component (logo is just placeholder for our logo, we can add the actual picture with "Spotisize" afterwards)
- Installed tailwind, edited config file and global.css
- Created routes and page for "About" and "Contact Us" tabs

### CODE REVIEW

**Review by Maxty99 — APPROVED** [review]
LGTM

**Comment by Maxty99** [comment]
Acc wait on second thought can't we just put this in the Layout section of the main app instead of adding the component to every page

**Comment by patel-aaryan** [comment]
> Acc wait on second thought can't we just put this in the Layout section of the main app instead of adding the component to every page

**Comment by patel-aaryan** [comment]
> Acc wait on second thought can't we just put this in the Layout section of the main app instead of adding the component to every page

We can if we want to have navbar in every page

**Comment by patel-aaryan** [comment]
Shit I accidentally closed pull request. We can discuss more on friday when we all connect

**Pull request closed without merging**
